version: "3"
services:
    app:
        build: docker/php-fpm
        container_name: app
        ports:
            - 9010:9000
        volumes:
            - ./:/var/www/devicetracker
        links:
            - redis
    nginx:
        build: docker/nginx
        container_name: nginx
        tty: true
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/devicetracker
        links:
            - app
    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        ports:
          - "${REDIS_PORT}:6379"
